#
###################################
# Site wide configuration
####################################
#
title: 4ox"'"log
email: mail@4ox.kr
description: 4ox"'" devlog powered by jekyll.
url: https://4ox.kr
keywords: ["Programming", "Web", "Nodejs"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 4ox
  avatar: leonids-logo.png
  job: "Web Developer"
  bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, France."
  email: mail@4ox.kr
  disqus-shortname: 4ox-kr
  twitter: 4oxmile #username
  facebook: woongmin #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: 4ox #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
